[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"


# A redirect rule with many of the supported properties
[[redirects]]
  from = "https://heartless.netlify.app"
  to = "https://heartless.uno"
  status = 301
  force = true

