[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"


# A redirect rule with many of the supported properties
[[redirects]]
  from = "https://heartless.netlify.app"
  to = "https://hear.tless.one"
  status = 301
  force = true

[[redirects]]
  from = "https://tless.one"
  to = "https://hear.tless.one"
  status = 301
  force = true

[functions]
  # Directory with serverless functions, including background
  # functions, to deploy. This is relative to the base directory
  # if one has been set, or the root directory if
  # a base hasn’t been set.
  directory = "functions/"

