[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  # package = "@netlify/plugin-lighthouse"


# A redirect rule with many of the supported properties
[[redirects]]
  from = "https://heartless.netlify.app"
  to = "https://heartless.uno"
  status = 301
  force = true
  from = "https://discordo.cam"
  to = "https://heartless.uno"
  status = 301
  force = true
    from = "https://discordian.online"
  to = "https://heartless.uno"
  status = 301
  force = true
    from = "https://discordian.website"
  to = "https://heartless.uno"
  status = 301
  force = true
