[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"
  package = "@netlify/plugin-ghost-markdown@3.0.3"
  package = "@netlify/plugin-no-more-404@0.0.15"


# A redirect rule with many of the supported properties
[[redirects]]
  from = "https://heartless.netlify.app"
  to = "https://heartless.uno"
  status = 301
  force = true

